//
//  RecognitionResultViewModel.swift
//  Balık Avı - İstanbul Balık Avı
//
//  Created by Emir AKSU on 4.08.2024.
//

import Foundation

class RecognitionResultViewModel {
    
let fishDictionary: [String: String] = [
        "Opisthonema oglinum": "Atlantik İplik Ringa Balığı",
        "Sphyrna mokarran": "Büyük Çekiç Başlı Köpekbalığı",
        "Hiodon alosoides": "Goldeye",
        "Neogobius melanostomus": "Karadeniz Kayası, Kum Kaya Balığı",
        "Squalus acanthias": "Mahmuzlu Camgöz Köpek Balığı",
        "Leuciscus aspius": "Koca Ağız Balığı",
        "Xiphias gladius": "Kılıç Balığı",
        "Lutjanus cyanopterus": "Cubera balığı",
        "Acroteriobatus annulatus": "Afrika Cüce Vatozu",
        "Clupea harengus": "Atlantik Ringa Balığı",
        "Scaphirhynchus platorynchus": "Küçükburnu Mersin Balığı",
        "Arripis truttacea": "Avustralya Salmonu",
        "Micropterus notius": "Suwannee bass",
        "Scomberomorus commerson": "Palamut kolyozu",
        "Carcharhinus obscurus": "Kara Köpekbalığı",
        "Pterois volitans": "Aslan Balığı",
        "Epinephelus itajara": "Orfoz",
        "Mugil curema": "Beyaz Kefal",
        "Channa marulius": "Kobra Yılanbaş Balığı",
        "Nebrius ferrugineus": "Paslı Hemşire Köpekbalığı",
        "Rhincodon typus": "Balina Köpekbalığı",
        "Aetobatus narinari": "Kartal Vatozu",
        "Coregonus clupeaformis": "Gümüş Balığı",
        "Albula vulpes": "Kemik Balığı",
        "Epinephelus malabaricus": "Malabar Orfozu",
        "Platycephalus indicus": "Yassı Kafalı Balık",
        "Clarias gariepinus": "Afrika Kedibalığı, Karabalık",
        "Lepisosteus oculatus": "Benekli Yayıngiller",
        "Anguilla anguilla": "Avrupa Yılan Balığı",
        "Carcharhinus plumbeus": "Kum Kaplanı Köpekbalığı",
        "Enneacanthus gloriosus": "Güneş Balığı",
        "Leiostomus xanthurus": "Spot Balığı",
        "Lepomis megalotis": "Uzun Kulaklı Güneş Balığı",
        "Scorpaena guttata": "Kaliforniya Akrebi",
        "Channa argus": "Kuzey Yılanbaş Balığı",
        "Hephaestus fuliginosus": "Sooty Grunter",
        "Micropterus coosae": "Coosa Alabalığı",
        "Opsanus tau": "Kurbağa Balığı",
        "Paralabrax maculatofasciatus": "Pasifik Kum Balığı",
        "Paralichthys californicus": "Kaliforniya Pisi Balığı",
        "Semotilus corporalis": "Fallfish",
        "Carpiodes carpio": "Nehir Sazan Balığı",
        "Macquaria ambigua": "Altın Levrek,",
        "Oligoplites saurus": "Kızıl Orkinos",
        "Thymallus thymallus": "Avrupa Gravası",
        "Platichthys flesus": "Pisi Balığı",
        "Semotilus atromaculatus": "Dere kefali",
        "Epinephelus tukula": "Patates Morina",
        "Lutjanus fulviflamma": "Sarı Kuyruklu Levrek",
        "Barbus barbus": "Bayağı bıyıklı balık",
        "Hypophthalmichthys molitrix": "Gümüş Sazanı",
        "Prosopium williamsoni": "Montana Beyaz Balığı",
        "Epinephelus marginatus": "Kayalık Orfoz",
        "Thymallus arcticus": "Arktik Gravası",
        "Menticirrhus saxatilis": "Kingfish",
        "Moxostoma macrolepidotum": "Kırmızı Kılıç Balığı",
        "Blicca bjoerkna": "Tahta Balığı",
        "Epinephelus lanceolatus": "Dev Orfoz",
        "Moxostoma anisurum": "Gümüş Balığı",
        "Sebastes melanops": "Siyah Kayan Balığı",
        "Tautoga onitis": "Siyah Balık",
        "Tylosurus crocodilus": "Timsah İğne Balığı",
        "Caranx sexfasciatus": "Büyük Göz Trevallies Balığı",
        "Cynoscion regalis": "Zayıf Balığı",
        "Labrus bergylta": "Kikla",
        "Lutjanus gibbus": "Humpback Red Snapper",
        "Pachymetopon blochii": "Pachymetopon blochii",
        "Scomber japonicus": "Kolyoz",
        "Epinephelus striatus": "Nassau Orfozu",
        "Gadus morhua": "Atlantik Morinası",
        "Lutjanus argentiventris": "Sarı Kuyruklu Kızıl Balık",
        "Scarus guacamaia": "Gökkuşağı Papağan Balığı",
        "Sphoeroides maculatus": "Kuzey Puffer Balığı",
        "Belone belone": "Zargana",
        "Elagatis bipinnulata": "Gökkuşağı Koşucusu",
        "Lutjanus decussatus": "Şeritli Orfoz",
        "Micropterus treculii": "Guadalupe Bass",
        "Myliobatis aquila": "Fulya balığı",
        "Paralabrax nebulifer": "Çizgili Deniz Levreği",
        "Plectropomus laevis": "Kara Eyerli Mercan Alabalığı",
        "Pollachius pollachius": "Sarı Mezgit Balığı",
        "Amphistichus argenteus": "Barred Surfperch",
        "Epinephelus merra": "Siyah Benekli Kaya Morina Balığı",
        "Macquaria novemaculeata": "Avustralya Morinası",
        "Dasyatis pastinaca": "Dikenli Vatoz",
        "Gymnosarda unicolor": "Köpek Dişli Ton Balığı",
        "Ptychocheilus oregonensis": "Kuzey Pike-Minnow",
        "Salvelinus confluentus": "Boğa Alabalığı",
        "Sparisoma rubripinne": "Kırmızı Yüzgeçli Papağan Balığı",
        "Cantherhines pullus": "Orta Atlantik File Balığı",
        "Sander lucioperca": "Sudak",
        "Acipenser transmontanus": "Beyaz Mersin Balığı",
        "Carcharhinus melanopterus": "Siyah Yüzgeçli Köpekbalığı",
        "Silurus glanis": "Yayın Balığı",
        "Anisotremus surinamensis": "Sarı Çizgili Mırmır",
        "Epinephelus coioides": "Portakal Benekli Orfoz",
        "Scyliorhinus canicula": "Küçük Kedi Balığı",
        "Atractosteus spatula": "Alligator Gar",
        "Ophiodon elongatus": "Lingcod",
        "Prionotus evolans": "Gurnard Balığı",
        "Rhomboplites aurorubens": "Vermilion Snapper",
        "Carcharhinus leucas": "Boğa Köpekbalığı",
        "Salmo salar": "Atlantik Somonu",
        "Esox americanus americanus": "Kırmızı Pullu Turna",
        "Stenotomus chrysops": "Scup Balığı",
        "Triakis semifasciata": "Leopar Köpekbalığı",
        "Rhabdosargus sarba": "Goldline Balığı",
        "Merlangius merlangus": "Mezgit",
        "Sebastes miniatus": "Vermilion Rockfish",
        "Scorpaenichthys marmoratus": "Cabezon Balığı",
        "Lota lota": "Burbot Balığı",
        "Lutjanus fulvus": "Kara Snapper",
        "Lutjanus jocu": "Dog Snapper",
        "Makaira nigricans": "Atlantik Mavi Marlin",
        "Pagrus auratus": "Altın Snapper",
        "Pseudopleuronectes americanus": "Amerikan Pisi Balığı",
        "Synodus foetens": "Kuzey Kertenkele Balığı",
        "Acanthopagrus butcheri": "Siyah Brim",
        "Acipenser fulvescens": "Göl Mersin Balığı",
        "Cephalopholis miniata": "Coral Trout",
        "Mustelus canis": "Pürüzsüz Köpekbalığ",
        "Nocomis micropogon": "River Chub",
        "Oncorhynchus nerka": "Kırmızı Somon",
        "Raja clavata": "Dikenli Vatoz",
        "Caranx melampygus": "Mavi Trevally",
        "Arripis trutta": "Avustralya Salmonu",
        "Carassius carassius": "Sazan",
        "Centropristis striata": "Siyah Deniz Levreği",
        "Lutjanus bohar": "Two-spot Red Snapper",
        "Seriola lalandi": "Sarı Kuyruk",
        "Paralabrax clathratus": "Barred Sand Bass",
        "Istiophorus albicans": "Atlantik Yelken Balığı",
        "Menticirrhus americanus": "Güney Kingfish",
        "Trachinotus goodei": "Palometa",
        "Epinephelus fasciatus": "Siyah Çizgili Orfoz",
        "Lates calcarifer": "Barramundi",
        "Triaenodon obesus": "Beyaz Uçlu Resif Köpekbalığı",
        "Hippoglossus stenolepis": "Pasifik Halibut",
        "Carcharias taurus": "Kum Kaplanı",
        "Oncorhynchus gorbuscha": "Pembe Somon",
        "Sander canadensis": "Kanada Sudak Balığı",
        "Cyprinus rubrofuscus": "Koi Balığı",
        "Dorosoma cepedianum": "Gizzard Shad",
        "Oncorhynchus tshawytscha": "Kral Somon",
        "Scomberomorus regalis": "Atlantik İspanyol Uskumru Balığı",
        "Maccullochella peelii": "Murray Morina Balığı",
        "Oncorhynchus keta": "Chum Somon",
        "Gnathanodon speciosus": "Altın Trevally",
        "Sparisoma aurofrenatum": "Kırmızı Benekli Papağan Balığı",
        "Tilapia sparrmanii": "Sparrman Tilapyası",
        "Alosa sapidissima": "Amerikan Şad Balığı",
        "Canthigaster rostrata": "Enine Bantlı Kirpi Balığı",
        "Centrarchus macropterus": "Yeşil Güneş Balığı",
        "Mycteroperca bonaci": "Kara Orfoz",
        "Carcharodon carcharias": "Büyük Beyaz Köpekbalığı",
        "Lutjanus mahogoni": "Mahogany Snapper",
        "Channa striata": "Yılan Başı Balığı",
        "Bodianus rufus": "İspinoz Balığı",
        "Micropterus floridanus": "Florida Largemouth Bass",
        "Lepomis punctatus": "Bantlı Güneş Balığı",
        "Cnidoglanis macrocephalus": "Avustralya Kedi Balığı",
        "Heterodontus portusjacksoni": "Port Jackson Köpekbalığı",
        "Oncorhynchus clarkii": "Clark’ın Alabalığı",
        "Sarda sarda": "Palamut",
        "Sparisoma viride": "Mavi Papağan Balığı",
        "Ictiobus bubalus": "Küçükbaş Buffalolar",
        "Variola louti": "Sarı Benekli Hani",
        "Euthynnus alletteratus": "Çatal Kuyruklu Palamut",
        "Abudefduf saxatilis": "Çavuş Balığı",
        "Menidia menidia": "Atlantik Menhaden",
        "Anguilla rostrata": "Amerikan Yılan Balığı",
        "Alectis ciliaris": "Afrika Kriko Balığı",
        "Caranx latus": "At Kafalı Kriko Balığı",
        "Rhizoprionodon terraenovae": "Atlantik Keskin Burun Köpekbalığı",
        "Epinephelus morio": "Kırmızı Orfoz",
        "Morone mississippiensis": "Sarı Levrek",
        "Scardinius erythrophthalmus": "Kızılgöz Balığı",
        "Scomber scombrus": "Uskumru",
        "Ameiurus catus": "Beyaz Kedi Balığı",
        "Mycteroperca microlepis": "Gagata Orfoz",
        "Seriola rivoliana": "Amberjack",
        "Carcharhinus limbatus": "Siyah Uçlu Köpekbalığı",
        "Thunnus atlanticus": "Siyah Kuyruk Ton Balığı",
        "Cyprinus carpio carpio": "Sazan",
        "Strongylura marina": "Atlantik İğne Balığı",
        "Morone chrysops X Morone saxatilis": "Hibrit Şeritli Levrek",
        "Lachnolaimus maximus": "Domuz Balığı",
        "Sphyrna tiburo": "Kepçe Burunlu Çekiç Köpekbalığı",
        "Lepisosteus platyrhincus": "Florida Gar Balığı",
        "Lobotes surinamensis": "Tripletail",
        "Lutjanus argentimaculatus": "Mangrove Kırmızı Balığı",
        "Cephalopholis cruentata": "Kırmızı Benekli Hani",
        "Rachycentron canadum": "Kob Balığı",
        "Carassius auratus": "Japon Balığı",
        "Ginglymostoma cirratum": "Dadı Köpekbalığı",
        "Oncorhynchus kisutch": "Gümüş Somon",
        "Salvelinus namaycush": "Göl Alabalığı",
        "Parachromis managuensis": "Jaguar Çiklit",
        "Ctenopharyngodon idella": "Çim Sazanı",
        "Paralichthys lethostigma": "Güney Flounder",
        "Platycephalus fuscus": "Düz Başlı Balık",
        "Astronotus ocellatus": "Oscar Balığı",
        "Esox masquinongy": "Muskie",
        "Bagre marinus": "Deniz Kedi Balığı",
        "Micropterus punctulatus": "Benekli Siyah Bas",
        "Pylodictis olivaris": "Düz Baş Kedi Balığı",
        "Paralichthys dentatus": "Yaz Flounder",
        "Caranx ignobilis": "Dev Kriko Balığı",
        "Morone chrysops": "Beyaz Levrek",
        "Selene vomer": "Ay Levrek Balığı",
        "Lutjanus campechanus": "Kırmızı Snapper",
        "Dicentrarchus labrax": "Avrupa Levrek",
        "Abramis brama": "Mersin Morinası",
        "Scomberomorus maculatus": "İspanyol Uskumru",
        "Oreochromis aureus": "Mavi Tilapiya",
        "Lutjanus synagris": "Sarı Gözlü Snapper",
        "Ictalurus furcatus": "Mavi Kedi Balığı",
        "Thunnus albacares": "Sarı Kuyruk Ton Balığı",
        "Morone americana": "Beyaz Perch",
        "Carangoides bartholomaei": "Sarı Kriko Balığı",
        "Scomberomorus cavalla": "Kral Uskumru",
        "Lepisosteus osseus": "Uzun Burunlu Gar Balığı",
        "Caranx crysos": "Mavi Kriko Balığı",
        "Haemulon plumierii": "Beyaz Kepçe Balığı",
        "Megalops atlanticus": "Atlantik Tarpon",
        "Elops saurus": "Teneke Balığı",
        "Acanthocybium solandri": "Wahoo",
        "Lutjanus analis": "Mutton Snapper",
        "Mugil cephalus": "Düz Burun Kefal",
        "Tinca tinca": "Tatlı Su Turnası",
        "Anisotremus virginicus": "Sarı Kurdele Balığı",
        "Trachinotus falcatus": "Pompano",
        "Acanthurus chirurgus": "Mavi Cerrah Balığı",
        "Ocyurus chrysurus": "Sarı Kuyruk Snapper",
        "Salmo trutta": "Kahverengi Alabalık",
        "Cynoscion nebulosus": "Gri Spotted Seatrout",
        "Seriola dumerili": "Greater Amberjack",
        "Centropomus undecimalis": "Common Snook",
        "Ambloplites rupestris": "Rock Bass",
        "Lepomis cyanellus": "Yeşil Güneş Balığı",
        "Pomoxis annularis": "Beyaz Crappie",
        "Sander vitreus": "Walleye",
        "Cymatogaster aggregata": "Shiner Surfperch",
        "Aplodinotus grunniens": "Freshwater Drum",
        "Caranx hippos": "Common Jack",
        "Esox niger": "Zincir Pickerel",
        "Ameiurus melas": "Siyah Kedi Balığı",
        "Amia calva": "Bowfin",
        "Cyprinus carpio": "Sazan",
        "Lagodon rhomboides": "Deniz Kırlangıcı",
        "Perca flavescens": "Sarı Perch",
        "Pomoxis nigromaculatus": "Siyah Crappie",
        "Micropogonias undulatus": "Atlantik Croaker",
        "Lepomis gulosus": "WarMouth",
        "Lutjanus apodus": "Schoolmaster Snapper",
        "Perca fluviatilis": "Avrupa Perch",
        "Ariopsis felis": "Deniz Kedi Balığı",
        "Ictalurus punctatus": "Kanal Kedi Balığı",
        "Ameiurus natalis": "Sarı Kedi Balığı",
        "Caranx ruber": "Bar Jack",
        "Catostomus commersonii": "Beyaz Sazan",
        "Cichla ocellaris": "Peacock Bass",
        "Hypanus sabinus": "Atlantik Stingray",
        "Rutilus rutilus": "Kızılgöz Balığı",
        "Trachinotus carolinus": "Florida Pompano",
        "Ameiurus nebulosus": "Kahverengi Kedi Balığı",
        "Balistes capriscus": "Gri Tetik Balığı",
        "Orthopristis chrysoptera": "Pembe Balık",
        "Acanthopagrus australis": "Çizgili Levrek",
        "Hypanus americanus": "Sarı Yüzgeçli Deniz Çipurası",
        "Lepomis microlophus": "Lüfer",
        "Morone saxatilis": "Çizgili Levrek",
        "Pomatomus saltatrix": "Koyun Kafalı Balık",
        "Archosargus probatocephalus": "Kırmızı Göbekli Güneş Balığı",
        "Mayaheros urophthalmus": "Maya Çiklit Balığı",
        "Lepomis gibbosus": "Kabarcıklı Güneş Balığı",
        "Lepomis macrochirus": "Mavi Yüzgeçli Güneş Balığı",
        "Lutjanus griseus": "Grida",
        "Esox lucius": "Kuzey Turna Balığı",
        "Coryphaena hippurus": "Mahi Mahi",
        "Lepomis auritus": "Kırmızı Kulaklı Güneş Balığı",
        "Sphyraena barracuda": "Baraküda",
        "Herichthys cyanoguttatus": "Teksas Cikleti",
        "Pogonias cromis": "Siyah Davul Balığı",
        "Micropterus dolomieu": "Küçük Ağızlı Levrek",
        "Micropterus salmoides": "Büyük Ağızlı Levrek",
        "Salvelinus fontinalis": "Alabalık",
        "Oncorhynchus mykiss": "Gökkuşağı Alabalı��ı",
        "Sciaenops ocellatus": "Kırmızı Davul Balığı"
    ]


    let fishFamilies: [String: String] = [
        "Dorosomatidae": "gözgöz balığıgiller",
        "Sphyrnidae": "Çekiç Balığıgiller",
        "Hiodontidae": "gözgöz balığıgiller",
        "Gobiidae": "Kayabalığıgiller",
        "Squalidae": "Camgözgiller",
        "Cyprinidae": "Sazangiller",
        "Xiphiidae": "Kılıçlıgiller",
        "Lutjanidae": "Levrek Balığıgiller",
        "Rhinobatidae": "Gergedangiller",
        "Acipenseridae": "Mersin Balığıgiller",
        "Arripidae": "Levrek Balığıgiller",
        "Centrarchidae": "Güneş Balığıgiller",
        "Scombridae": "Uskumrugiller",
        "Carcharhinidae": "Harharyasgiller",
        "Scorpaenidae": "İskorpitgiller",
        "Epinephelidae": "Ofroz Balığıgiller",
        "Mugilidae": "Kefalgiller",
        "Channidae": "Yılanbaş Balığıgiller",
        "Ginglymostomatidae": "Hemşire Köpekbalığıgiller",
        "Rhincodontidae": "Köpekbalığıgiller",
        "Myliobatidae": "Şineli Balığıgiller",
        "Salmonidae": "Alabalıkgiller",
        "Albulidae": "Uzun Balığıgiller",
        "Platycephalidae": "Şapkalı Balığıgiller",
        "Clariidae": "Hava Soluyan Yayıngiller",
        "Lepisosteidae": "Kafatası Balığıgiller",
        "Anguillidae": "Yılan Balığıgiller",
        "Sciaenidae": "Kıskaçgiller",
        "Terapontidae": "Levrek Balığıgiller",
        "Batrachoididae": "kurbağabalığıgiller",
        "Serranidae": "levrekgiller",
        "Paralichthyidae": "yassı levrek balığıgiller",
        "Catostomidae": "yüzgeç balığıgiller",
        "Percichthyidae": "percichthyid balığıgiller",
        "Carangidae": "İstavritgiller",
        "Pleuronectidae": "Pisi Balıkları",
        "Sebastidae": "kaya balığıgiller",
        "Labridae": "Lapinagiller",
        "Belonidae": "Zargana",
        "Sparidae": "İzmaritgiller",
        "Gadidae": "Mezgitgiller",
        "Scaridae": "Papağanbalığıgiller",
        "Tetraodontidae": "Balon balıkları",
        "Embiotocidae": "kemancık balığıgille",
        "Dasyatidae": "Dikenli Uyuşturan Balığıgiller",
        "Monacanthidae": "Dikenli Çütreler",
        "Percidae": "levrekgiller",
        "Siluridae": "gato balığıgiller",
        "Haemulidae": "Gargur Balıkları",
        "Scyliorhinidae": "Kedibalığıgiller",
        "Hexagrammidae": "altınbaş balığıgiller",
        "Triglidae": "kaya balığıgiller",
        "Esocidae": "pike balığıgiller",
        "Triakidae": "Köpek Balığı",
        "Cottidae": "Dere İskorpitigiller",
        "Lotidae": "lot balığıgiller",
        "Istiophoridae": "mızrak balığıgiller",
        "Synodontidae": "Kertenkele balığı",
        "Rajidae": "Vatozgiller",
        "Latidae": "levrekgiller",
        "Odontaspididae": "Köpek Balığı",
        "Cichlidae": "cichlid balığıgiller",
        "Lamnidae": "Köpek Balığı",
        "Plotosidae": "kedi balığıgiller",
        "Heterodontidae": "Balon balıkları",
        "Pomacentridae": "kıskaç balığıgiller",
        "Atherinopsidae": "kılıç balığıgiller",
        "Moronidae": "levrekgiller",
        "Ictaluridae": "kedi balığıgiller",
        "Lobotidae": "lobit balığıgiller",
        "Rachycentridae": "kılçık balığıgiller",
        "Ariidae": "kedi balığıgiller",
        "Megalopidae": "tarpon balığıgiller",
        "Elopidae": "tarpon balığıgiller",
        "Acanthuridae": "Cerrah Balıkları",
        "Centropomidae": "levrekgiller",
        "Amiidae": "kel turna balığıgiller",
        "Balistidae": "Tetik Balığı",
        "Pomatomidae": "Lüfergiller",
        "Coryphaenidae": "Lambuka",
        "Sphyraenidae": "İskarmozgiller"
    ]

    
}
